language: node_js

before_install:
  # - npm install -g yarn
  # - yarn add global ruby
  - gem install sass

script:
  npm run ci
after_script:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
