#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

try ./script/compile-css
try npm run-script ci -- --serial --fail-fast


temp_file=$(mktemp)

do_progress_quiet "Checking that command line displays help" \
  ./bin/css-plus --help

do_progress_quiet "Sanity-checking command line" \
  ./bin/css-plus --css ./test/motivation/all.css --html ./test/motivation/_input.xhtml --output "${temp_file}"

try rm "${temp_file}" "${temp_file}.map" # delete the file afterwards



if [[ ${CI} != "true" ]]; then
  do_progress_quiet "Generating Javascript Coverage report at ./coverage/index.html" \
    "$(npm bin)/nyc" report --reporter=html

  # Generate an HTML report (if genhtml is installed)
  if [[ -n "$(which genhtml)" ]]; then
    do_progress_quiet "removing empty .lcov files" \
      find . -size 0 -name "*.lcov" -delete
    do_progress_quiet "Generating HTML and CSS Coverage report at ./coverage-css-and-html/index.html" \
      genhtml --quiet --output ./coverage-css-and-html/ $(find ./test/ -name "*.lcov")
  fi
fi

do_progress_quiet "Linting JavaScript files" \
  npm run-script lint
