#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

do_progress_quiet "Compiling motivation example" \
  "$(npm bin)/node-sass" --source-map true test/motivation/all.scss test/motivation/all.css

for filename in $(ls ./test/*/*.less); do
  filename="${filename%.*}" # strip off the extension
  do_progress_quiet "compiling ${filename}" \
    "$(npm bin)/lessc" --source-map "${filename}.less" "${filename}.css"
done
