#!/bin/bash
set -e

sass test/motivation/all.scss test/motivation/all.css

for filename in $(ls ./test/*/*.less)
do
  echo "compiling ${filename}"
  filename="${filename%.*}" # strip off the extension
  $(npm bin)/lessc --source-map "${filename}.less" "${filename}.css"
done
