#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

[[ $1 ]] || die "An argument must be passed in. It is a regular expression of a title to match"

try ./script/rebuild-tests -- --match $@
