#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

try ./script/build

_say '======================================================'
_say ' Remember to add a `debugger` statement in your code!'
_say '======================================================'

npm run-script debugger -- $@
