#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

npm test || exit 111

# Generate an HTML report (if genhtml is installed)
if [[ -n "$(which genhtml)" ]]; then
  do_progress_quiet "Generating HTML and CSS Coverage report at ./coverage/" \
    genhtml --quiet --output ./coverage/ $(find ./test/ -name "*.lcov")
fi
