#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

bake_command="./bin/css-plus"

less_file="./data/style.less"
css_file="./data/style.css"
raw_file="./data/entrepreneurship-raw.xhtml"
baked_file="./data/entrepreneurship-baked.xhtml"
pdf_file="./data/entrepreneurship-baked.pdf"

do_progress_quiet "Compiling LESS file" \
  $(npm bin)/lessc --source-map "${less_file}" "${css_file}"

do_progress "Baking HTML file"
"${bake_command}" --css "${css_file}" --html "${raw_file}" --output "${baked_file}" $@

do_progress_quiet "Building PDF" \
  prince --insecure "${baked_file}" --output="${pdf_file}"

_say "Baking succeeded. Check out ${baked_file} and ${pdf_file}"
